Add Scilpy version - part 1
scilus/scilpy pull request #1100
Opened 2024-12-12 19:20 UTC by elyz081

Fix issue #760 

Part 1 of adding the Scilpy version to the scripts

2024-12-18 03:15 UTC, EmmaRenauld requested changes
Good to go after my comment has been adressed

2024-12-18 03:15 UTC, EmmaRenauld commented on scripts/scil_bundle_score_many_bundles_one_tractogram.py
> +                                formatter_class=argparse.RawTextHelpFormatter,
I think here you need to keep the `+ tractometry_description`

2025-01-21 15:11 UTC, karanphil requested changes
Great job! I found a few things to adjust but it should be quick. Good to go after that!

2025-01-21 15:11 UTC, karanphil commented on scripts/scil_aodf_metrics.py
> +
Empty line here. It should be removed to be as the others.

2025-01-21 15:11 UTC, karanphil commented on scripts/scil_bundle_mean_fixel_afd_from_hdf5.py
> +
Same here, remove the line.

2025-01-21 15:11 UTC, karanphil commented on scripts/scil_connectivity_compare_populations.py
> +[1] Rubinov, Mikail, and Olaf Sporns. "Complex network measures of brain
Missing the "References:"

2025-01-21 15:11 UTC, karanphil commented on scripts/scil_bundle_shape_measures.py
> +References:
Reference*

2025-01-21 15:11 UTC, karanphil commented on scripts/scil_connectivity_compute_pca.py
> + Jones DK. Dimensionality reduction of diffusion MRI measures for improved
Add tabs to make it clearer (like other scripts).

2025-01-21 15:11 UTC, karanphil commented on scripts/scil_dwi_prepare_eddy_command.py
> +from dipy.io.gradients import read_bvals_bvecs
Why did you move that? If I am not mistaken, it should be with the libraries like numpy.

2025-01-21 15:12 UTC, karanphil commented on scripts/scil_aodf_metrics.py
> +
Remove this line also, just one line between paragraphs.

2025-01-21 15:18 UTC, karanphil reviewed
Other comments!

2025-01-21 15:18 UTC, karanphil commented on scripts/scil_bundle_mean_fixel_afd.py
> +    [1] Raffelt, D., Tournier, JD., Rose, S., Ridgway, GR., Henderson, R.,
Remove one tab here.

2025-01-21 15:18 UTC, karanphil commented on scripts/scil_bundle_mean_fixel_afd.py
> +
Remove line.

2025-01-27 20:26 UTC, karanphil approved these changes
One small comments and then GTG!

2025-01-27 20:26 UTC, karanphil commented on scripts/scil_aodf_metrics.py
> +Where and How Asymmetry Occurs in the White Matter." bioRxiv. 2022 Jan 1;
Missings tabs here. (Not on the first line)

2025-01-27 20:31 UTC, karanphil commented on scripts/scil_dwi_prepare_eddy_command.py
> +from dipy.io.gradients import read_bvals_bvecs
@elyz081 this has not been addressed.

2025-01-27 21:37 UTC, elyz081 commented on scripts/scil_dwi_prepare_eddy_command.py
>  from scilpy.io.utils import (add_overwrite_arg, add_verbose_arg,
@karanphil the Dipy comment was resolved here

2025-01-28 00:05 UTC, karanphil approved these changes

2025-01-28 01:52 UTC, EmmaRenauld approved these changes
GTG!

2025-01-28 03:07 UTC, merged