Add Scilpy version - part 2
scilus/scilpy pull request #1106
Opened 2024-12-12 20:03 UTC by elyz081

Fix issue https://github.com/scilus/scilpy/issues/760

Part 2 of adding the Scilpy version to the scripts

2024-12-12 20:03 UTC, pep8speaks commented
Hello @elyz081, Thank you for submitting the Pull Request !















* In the file [`scripts/scil_frf_ssst.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_frf_ssst.py):

> [Line 12:12](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_frf_ssst.py#L12): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace





* In the file [`scripts/scil_gradients_generate_sampling.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_generate_sampling.py):

> [Line 16:12](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_generate_sampling.py#L16): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 18:80](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_generate_sampling.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)





* In the file [`scripts/scil_gradients_round_bvals.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_round_bvals.py):

> [Line 33:33](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_round_bvals.py#L33): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 34:33](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_round_bvals.py#L34): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

* In the file [`scripts/scil_gradients_validate_correct.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_validate_correct.py):

> [Line 27:80](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_gradients_validate_correct.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)



















* In the file [`scripts/scil_labels_remove.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_labels_remove.py):

> [Line 34:1](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_labels_remove.py#L34): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 54:1](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_labels_remove.py#L54): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace















* In the file [`scripts/scil_mti_maps_MT.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_mti_maps_MT.py):

> [Line 82:80](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_mti_maps_MT.py#L82): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`scripts/scil_mti_maps_ihMT.py`](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_mti_maps_ihMT.py):

> [Line 88:80](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_mti_maps_ihMT.py#L88): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 89:80](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_mti_maps_ihMT.py#L89): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 98:80](https://github.com/scilus/scilpy/blob/e6b4d611c8afb7214b8b9cf38525651f5e8a3291/scripts/scil_mti_maps_ihMT.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2024-12-18 03:20 UTC, EmmaRenauld approved these changes

2025-01-21 15:24 UTC, karanphil requested changes
Good job! Again, small adjustments needed for it to be consistent. Good to go after that!

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_NODDI_maps.py
> +
Remove this empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_NODDI_priors.py
> +
Remove this empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_freewater_maps.py
> +
Remove this empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_freewater_maps.py
> +    [1] Pasternak 0, Sochen N, Gur Y, Intrator N, Assaf Y.
Remove one tab.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_frf_ssst.py
> +References:
Reference*

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_gradients_generate_sampling.py
> +References:
Reference*

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_gradients_generate_sampling.py
> +
Remove empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_labels_combine.py
> +
Remove empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_labels_dilate.py
> +
Remove empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_labels_dilate.py
> +References:
Reference*

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_labels_dilate.py
> +    [1] Al-Sharif N.B., St-Onge E., Vogel J.W., Theaud G.,
Remove one tab.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_labels_remove.py
> +
Remove empty line.

2025-01-21 15:24 UTC, karanphil commented on scripts/scil_labels_remove.py
> +References:
Reference*

2025-01-27 20:33 UTC, karanphil approved these changes
GTG! Wait for the part 1 to be merged, then update master.

2025-01-28 16:24 UTC, merged