Add MT script
scilus/scilpy pull request #310
Opened 2020-09-01 19:47 UTC by Manonedde

Script to compute MT maps.
Check code and test. 
Data PR (HoG subject) : https://drive.google.com/file/d/1qxzVORKmFPRa5ZXmxPTaR8KIx-Pbla4y/view?usp=sharing

2020-09-24 15:41 UTC, arnaudbore approved these changes

2020-09-24 18:07 UTC, GuillaumeTh requested changes

2020-09-24 18:07 UTC, GuillaumeTh commented on scripts/scil_compute_MT_maps.py
> +2008;60(6):1396‑407.
@Manonedde could you please remove the - in `1396‑407` and readd it. You copy paste directly the URL and this character is not the real `-`.

2020-09-24 18:07 UTC, GuillaumeTh commented on scripts/scil_compute_MT_maps.py
> +# -*- coding: utf-8 -*-
#!/usr/bin/env python3

2020-11-04 19:56 UTC, mdesco approved these changes
Thanks Manon for this.

To me, ready to go! Good job!

2020-11-04 19:56 UTC, mdesco commented on scripts/scil_compute_MT_maps.py
> +                   help='Path to B1 coregister map to MT contrasts.')
this option does not work. Please correct. If I remove the action='store_true', it works.

2020-11-05 14:46 UTC, merged