fix memory issue dti metrics
scilus/scilpy pull request #353
Opened 2020-11-09 18:57 UTC by arnaudbore

2020-11-09 18:57 UTC, pep8speaks commented
Hello @arnaudbore, Thank you for submitting the Pull Request !

* In the file [`scripts/scil_compute_dti_metrics.py`](https://github.com/scilus/scilpy/blob/0d8c281c99fa50ec3a45d34f1757493cf2eb70bf/scripts/scil_compute_dti_metrics.py):

> [Line 287:20](https://github.com/scilus/scilpy/blob/0d8c281c99fa50ec3a45d34f1757493cf2eb70bf/scripts/scil_compute_dti_metrics.py#L287): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 287:22](https://github.com/scilus/scilpy/blob/0d8c281c99fa50ec3a45d34f1757493cf2eb70bf/scripts/scil_compute_dti_metrics.py#L287): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2020-11-10 13:58 UTC, mdesco approved these changes
This works well!

2020-11-10 14:15 UTC, GuillaumeTh requested changes
I will test after the fix

2020-11-10 14:15 UTC, GuillaumeTh commented on scripts/scil_compute_dti_metrics.py
> +        for i in [1, 2, 3]:
range(3)

2020-11-10 14:15 UTC, GuillaumeTh commented on scripts/scil_compute_dti_metrics.py
> +        for i in [1, 2, 3]:
After using range adapt below.

2020-11-10 14:15 UTC, GuillaumeTh commented on scripts/scil_compute_dti_metrics.py
> +        for i in [1, 2, 3]:
Same comment use range please

2020-11-10 14:15 UTC, GuillaumeTh commented on scripts/scil_compute_dti_metrics.py
> +        R = np.mean(data_diff, axis=-1)
np.mean(data_diff[..., ~gtab.b0s_mask], axis=-1, dtype=np.float32)

2020-11-10 15:54 UTC, GuillaumeTh approved these changes

2020-11-10 15:54 UTC, merged