BF: visualise bundles mosaic when no streamlines
scilus/scilpy pull request #539
Opened 2022-01-18 20:38 UTC by arnaudbore

2022-01-18 20:42 UTC, GuillaumeTh requested changes

2022-01-18 20:42 UTC, GuillaumeTh commented on scripts/scil_visualize_bundles_mosaic.py
> +                if len(streamlines) != 0:
Only `if len(streamlines):`

2022-01-18 20:42 UTC, GuillaumeTh commented on scripts/scil_visualize_bundles_mosaic.py
> +            if len(streamlines) != 0:
Only `if len(streamlines):`

2022-01-18 21:03 UTC, GuillaumeTh approved these changes

2022-01-18 21:11 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-01-18 21:36 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-01-18 22:05 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-01-19 14:21 UTC, GuillaumeTh approved these changes

2022-01-19 14:21 UTC, merged