ENH: scil scoring unique streamlines
scilus/scilpy pull request #592
Opened 2022-06-28 10:55 UTC by AntoineTheb

This PR is to add an option to the scil scoring script to assign streamlines to the first bundle (valid or invalid) they fit in and not to all corresponding bundles (in the case of overlapping ROIs). This brings the behavior of the script closer to the Tractometer and makes the "VC/IC/NC" ratios to be accurate. 

Data to test: 

Command to test:

Ground truth FiberCup with itself:

```bash 
scil_score_tractogram.py FiberCupGroundTruth_all.tck ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data/scil_scoring_config.json prob_tracking_test --gt_dir ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data --reference ~/braindata/databases/fibercup/simulated/MICCAI2015/masks/wm.nii.gz --compute_ic --unique --no_empty -v
```

Prob tracking on the FiberCup:

```bash 
scil_score_tractogram.py tracking_prob_interface_300_075.trk ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data/scil_scoring_config.json prob_tracking_test --gt_dir ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data --reference ~/braindata/databases/fibercup/simulated/MICCAI2015/masks/wm.nii.gz --compute_ic --unique --no_empty -v
```

Det tracking on the FiberCup:

```bash 
scil_score_tractogram.py tracking_det_interface_300_075.trk ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data/scil_scoring_config.json det_tracking_test --gt_dir ~/braindata/databases/fibercup/simulated/MICCAI2015/scoring_data --reference ~/braindata/databases/fibercup/simulated/MICCAI2015/masks/wm.nii.gz --compute_ic --unique --no_empty -v
```

VS/IC/NC ratios should sum to 1.

@EmmaRenauld @arnaudbore

2022-06-28 10:56 UTC, pep8speaks commented
Hello @AntoineTheb, Thank you for submitting the Pull Request !

* In the file [`scripts/scil_score_tractogram.py`](https://github.com/scilus/scilpy/blob/33cd92f235df39dde5382137f31151101f8b9994/scripts/scil_score_tractogram.py):

> [Line 434:80](https://github.com/scilus/scilpy/blob/33cd92f235df39dde5382137f31151101f8b9994/scripts/scil_score_tractogram.py#L434): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

2022-06-28 11:35 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-06-28 11:35 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-06-28 14:29 UTC, EmmaRenauld reviewed
Some comments first, but I have not tested yet.

2022-06-30 13:35 UTC, AntoineTheb commented on scripts/scil_score_tractogram.py
>              extract_vb_vs(
Not sure what you mean by "wrong returns" in the docstring as no return is mentioned ... In fact almost no function in there mention returns (and arguments). I can add them if you want

2022-06-30 13:57 UTC, AntoineTheb commented on scripts/scil_score_tractogram.py
> +            all_ids = all_ids[not_vs_wps]
Problem is that if a streamline is a wpc for more than 1 bundle and a VC for another (or more), I would still end up with duplicates. I would need to check if a streamline is a duplicate wpc and then check if it is a duplicate vs. It's simpler to just assign it to the first bundle where it fits. I agree that I can skip the loops, then.

2022-06-30 15:40 UTC, AntoineTheb commented on scripts/scil_score_tractogram.py
> +        "VB": len(vb_sft_list),
Ah sorry, I thought they wouldn't be included if there were 0 streamlines included. I'll revert back the change.

2022-07-04 12:46 UTC, EmmaRenauld commented on scripts/scil_score_tractogram.py
>              extract_vb_vs(
In extract_vb_vs:

```
Returns
    -------
    tc_sft: StatefulTractogram
        SFT of true connections.
    wpc_sft: StatefulTractogram
        SFT of wrong-path-connections.
    fc_sft: StatefulTractogram
        SFT of false connections (streamlines that are too long).
    nc_streamlines: StatefulTractogram
        SFT of no connections (streamlines that loop)
    sft: StatefulTractogram
        SFT of remaining streamlines.
```

Is wrong, now it only returns 3 lists.

2022-07-04 16:09 UTC, EmmaRenauld commented on scripts/scil_score_tractogram.py
> +            all_ids = all_ids[not_vs_wps]
@mdesco

2022-07-07 14:49 UTC, AntoineTheb commented on scripts/scil_score_tractogram.py
>              extract_vb_vs(
Ah sorry I misinterpreted which method "that" referred to

2022-07-07 15:21 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-07 15:48 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-11 19:00 UTC, EmmaRenauld commented
I ran it on my ismrm data. I picked a submission at random so I don't know if it contained duplicates, but the script runs fine **(with a rebase on the master!!)**.

I tagged Max higher, to see with him what you want to do. But based on my experience, I will however come back stronger with what I said previously. I still think you should first verify that a wpc streamline is not a true connection of another bundle before removing it. Actually, I don't even compute wpc anymore when I use this script, it's often not clear what they represent. Ex below, in blue, the WPC of the cingulum is actually the uncinate fasciculus. Considering that in my config file, the UF comes after the cingulum, I will loose a lot of UF if I use your method! (In this case, I recover 43 streamlines / 429). See option remove_wpc_belonging_to_another_bundle; maybe some of what you need is already coded.

This makes me think, you should add a warning under the option `--unique` with: "Careful, order of bundles in the config file will influence your results".
 

![image](https://user-images.githubusercontent.com/4967417/178336852-3a01d066-3d8d-40ee-b153-868542949553.png)

2022-07-12 15:26 UTC, scil-admin commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-592/6/

2022-07-12 16:32 UTC, scil-admin commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-592/7/

2022-07-13 08:31 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-14 08:34 UTC, AntoineTheb commented
@EmmaRenauld can you send me the files you have used for your test of WPC vs VS ? I think I have a solution

2022-07-14 14:46 UTC, EmmaRenauld commented
It should work with 

```
scoring_data=$BrainData/databases/ismrm_2015/derivatives/scoring_data/output/version_2022
ref=$scoring_data/t1.nii.gz
config_file=$scoring_data/scoring_config.json

submissions_dir=$BrainData/databases/ismrm_2015/derivatives/submissions/output/anonymized_submissions_converted_tck
tractogram=$submissions_dir/1_0.tck

out_dir=test
mkdir test

scil_score_tractogram.py -v --no_empty --save_wpc_separately --gt_dir $scoring_data --reference $ref $tractogram $config_file $out_dir
```

With team 1_0, I get 18 duplicates between CC and Cingulum for the valid bundles so you can check if it works well +
for WPC, the cingulum_right_WPC contains parts of the valid bundles : UF right + SLF right + cingulum_left.

2022-07-19 19:02 UTC, arnaudbore requested changes
Need some work and maybe a quick discussion.

2022-07-19 19:02 UTC, arnaudbore commented on scripts/scil_score_tractogram.py
> +            all_ids = all_ids[not_vs_wps]
I sent a message to @mdesco . I agree with @EmmaRenauld you should not be removing a wps if it's a vs for another bundle

2022-07-20 00:45 UTC, mdesco commented on scripts/scil_score_tractogram.py
> +            all_ids = all_ids[not_vs_wps]
Also agree with @EmmaRenauld and @arnaudbore. Happy to have a short call to make sure we are the same page. @AntoineTheb I let you decide.

2022-07-21 08:27 UTC, AntoineTheb commented on scripts/scil_score_tractogram.py
> +        print(wpc_ids_list)
Woops sorry these were testing prints.

2022-07-21 08:57 UTC, AntoineTheb commented on scripts/scil_score_tractogram.py
> +            all_ids = all_ids[not_vs_wps]
@EmmaRenauld @arnaudbore @mdesco After speaking with Emmanuelle offline I agree with your points. I have added a potential fix in 10c56df7ad11241295ba25cf9adadd144aa2ab51, still waiting on data to test it.

2022-07-21 09:30 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-25 14:36 UTC, AntoineTheb commented
@EmmaRenauld @mdesco @arnaudbore I have added the modifications to assign WPCs to VCs (or actually, to assign to both and then filter out WPCs which are also VCs). 

As we can see in this example, the left cingulum does not end up with UF streamlines:

![image](https://user-images.githubusercontent.com/10272382/180801712-33412436-f923-4192-a93d-e20d2477771d.png)

While developing, I temporarily added checks to make sure that there were no duplicate streamlines. These checks have been removed prior to pushing.

2022-07-25 14:47 UTC, scil-admin commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-592/10/

2022-07-25 15:00 UTC, scil-admin commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-592/11/

2022-07-25 15:05 UTC, AntoineTheb commented
@EmmaRenauld looking at the comments to update them (don't worry I will), I realize that the updates change the behavior of the script: WPCs are either saved separately, or included as VS. However, it seems that they were previously never considered VS ? Is this something we want ? I feel this should be discussed.

2022-07-25 15:51 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-26 09:41 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-26 09:41 UTC, scil-admin commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-592/15/

2022-07-26 10:09 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-07-26 10:17 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-09-09 14:16 UTC, EmmaRenauld commented
@AntoineTheb  PR#600 was merged, you should merge with your PR to be sure.

2022-09-12 16:10 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-09-13 13:44 UTC, scil-admin commented
Build passed ! Good Job :beers: !

2022-09-16 17:55 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-592/19/

2022-09-22 22:19 UTC, AntoineTheb commented
Closing in favor of

2022-09-22 22:19 UTC, closed without merging