Project streamlines from/to wm/gm
scilus/scilpy pull request #640
Opened 2022-11-03 13:56 UTC by frheault

This new script expands on a previous version, projecting values from WM (streamlines) to the cortex (endpoints).
This version can project data from GM or WM to GM or WM (4 combos)

The data can come from metric maps (like before, FA, MD) or data_per_streamline or data_per_point (new).
The data_per_* can be from the .trk metadata or loaded from an array file.

This can be useful to project FA to the cortex, (WM->GM) or cortical thickness to the deep WM (GM->WM).
It can be used to visualize the distribution of streamlines and what they "touch" in a different way.

[test_for_kurt_project.zip](https://github.com/scilus/scilpy/files/9929743/test_for_kurt_project.zip)

2022-11-03 17:30 UTC, AntoineTheb requested changes
Following discussions that we had, the main should be cleaned up and functions should be moved into `scilpy` instead of mixing IO and logic.

2022-11-03 17:30 UTC, AntoineTheb commented on scripts/scil_project_streamlines_to_map.py
> +    mins, maxs, indices = _process_streamlines(sft.streamlines,
This and the following lines should be abstracted in a or multiple functions, which can reside in `scilpy`. The function(s) could return maps that can be saved in the main function. Overall, only IO should be in the main function.

2022-11-03 17:30 UTC, AntoineTheb commented on scripts/scil_project_streamlines_to_map.py
> +def _compute_streamline_mean(cur_ind, cur_min, cur_max, data):
This probably has a place in the library

2022-11-03 17:30 UTC, AntoineTheb commented on scripts/scil_project_streamlines_to_map.py
> +def _process_streamlines(streamlines, just_endpoints):
This probably has a place in the library and/or use functions that are already in the library

2022-11-03 17:30 UTC, AntoineTheb commented on scripts/scil_project_streamlines_to_map.py
> +def _project_metrics(curr_metric_map, count, orig_s, streamline_mean,
This could also go into the library. I would also add comments to tell the user that this function has side-effects instead of returns.

2023-02-28 18:29 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-02-28 19:56 UTC, merged