Fix: Add check_bbox_false to scil_score_bundles
scilus/scilpy pull request #641
Opened 2022-11-03 15:51 UTC by EmmaRenauld

Very small fix, remove bounding box valid checks.

2022-11-03 15:54 UTC, AntoineTheb approved these changes
Personnellement je mettrais ça _partout_ dans scilpy, mais c'est en effet une bonne idée d'ajouter ça au moins au scoring.

2022-11-03 15:54 UTC, AntoineTheb approved these changes
Personnellement je mettrais ça _partout_ dans scilpy, mais c'est en effet une bonne idée d'ajouter ça au moins au scoring.

2022-11-03 16:27 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-11-04 17:07 UTC, arnaudbore commented
Ok can you tell me a little bit about why this is such an issue ? Why we don't add a new arg to force bbox_valid_check to false ?

2022-11-07 17:28 UTC, EmmaRenauld commented
I'm not sure in other scripts, but here we are scoring tractograms that are potentially bad. 

But if I try to think about general cases, I would say the most probable case is when vertical bundles/streamlines go too far in the brainstem under the pons, into the spinal cord, they can go out of the image quite easily. Other ideas, @AntoineTheb ?

2022-11-07 17:35 UTC, AntoineTheb commented
Yeah that's usually the problem. The FiberCup's ground truth also goes out its volume.

2022-11-08 13:55 UTC, AntoineTheb commented
Thinking about it, it could probably be a good idea to add an option to the `argparser` to disable bbox checking (and make it easily available to other scripts, like the `--verbose` or `--force` option for example). I'll add an issue to remind myself to do it @arnaudbore @EmmaRenauld .

2022-11-08 14:01 UTC, arnaudbore commented
I agree, I don't like to automatically skip the bbox checking.

2022-11-08 16:13 UTC, EmmaRenauld commented
I agree too.

2022-11-08 18:46 UTC, EmmaRenauld commented
I made the change in all scripts using that check. Tested the whole pytest locally, it works.

2022-11-08 18:52 UTC, AntoineTheb commented
Cool ! Do you have a tractogram to test it ?

2022-11-08 19:21 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-11-08 19:23 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-11-08 19:45 UTC, EmmaRenauld commented
```
scoring_data=$BrainData/databases/ismrm_2015/derivatives/scoring_data/output/version_2022
ref=$scoring_data/t1.nii.gz
config_file_segmentation=$scoring_data/config_file_segmentation.json
config_file_tractometry=$scoring_data/config_file_tractometry.json
submissions_dir=$BrainData/databases/ismrm_2015/derivatives/submissions/output/anonymized_submissions_converted_tck

out_dir_root=tmp/
mkdir $out_dir_root

tractogram=$submissions_dir/3_3.tck
team=3_3
out_dir=$out_dir_root/$team;

# ------ Segmentation -------
scil_score_tractogram.py -f -v $tractogram $config_file_segmentation $out_dir --no_empty \
          --gt_dir $scoring_data --reference $ref --json_prefix tmp_  # ----------------> Fails

scil_score_tractogram.py -f -v $tractogram $config_file_segmentation $out_dir --no_empty \
          --gt_dir $scoring_data --reference $ref --json_prefix tmp_ --no_bbox_check  # --------> works

# ------ Final scoring -------
scil_score_bundles.py -f -v $config_file_tractometry $out_dir \
            --gt_dir $scoring_data --reference $ref;  # ----------------> Fails

scil_score_bundles.py -f -v $config_file_tractometry $out_dir \
            --gt_dir $scoring_data --reference $ref --bbox_check False;  # ------------------> Works.
```

2022-11-08 19:59 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-11-08 20:03 UTC, arnaudbore reviewed
Looking at all these modifications I think we have to really discuss about this implication because a lot of save and load were using bbox_valid_check=False and also now there is no distinctions between load and save and I don't really know if it's a good thing or not.

2022-11-08 20:36 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-11-09 13:52 UTC, EmmaRenauld commented on scripts/scil_extract_ushape.py
> +    sft = load_tractogram_with_reference(parser, args, args.in_tractogram)
`bbox_check=False` was not there to start with. I just removed the unnecessary newline.

2022-11-09 13:52 UTC, EmmaRenauld commented
Maybe I can remove this big commit for now, just so that scil_score_bundles can be usable in the next release, and we keep this bigger change for later?

2022-11-09 14:35 UTC, arnaudbore commented
@EmmaRenauld yes go !

2022-11-11 14:27 UTC, AntoineTheb commented on scripts/scil_extract_ushape.py
> +    sft = load_tractogram_with_reference(parser, args, args.in_tractogram)
I'm not sure what you mean with "no distinction between load and save" @arnaudbore

2022-11-11 18:49 UTC, EmmaRenauld commented
> there is no distinctions between load and save and I don't really know if it's a good thing or not.

Same as Antoine. I'm not sure either what you mean. I did not change the way it already was. Even better, I removed the default "False" in many places to make it optional.

But to try and answer... In the case where you need to use it because you have a faulty tractogram, there is a very good change that if a streamline is misplaced in the input, it will also be in the output, no matter what the script does. So I would guess that it's ok in general.

2022-11-11 19:30 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-641/6/

2022-11-11 19:33 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-641/7/

2022-11-11 20:13 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-12-08 19:24 UTC, EmmaRenauld commented
Is this ready, now that the release is done? @arnaudbore

2022-12-08 20:00 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2022-12-23 13:48 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-02-28 17:37 UTC, frheault commented
@EmmaRenauld  Can you update this code with master and then check if everything runs normally.
The master is now up to 3.10 (but should run in 3.8/3.9), so you may have to create a new venv.

2023-03-01 14:25 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-03-02 20:43 UTC, frheault commented
Out of curiosity, how did you pick which script to change immediately in this PR? Are they all script that runs even with invalid?

2023-03-03 03:26 UTC, EmmaRenauld commented
Hmmm.. it was 6 months ago so I don't exactly remember, sorry. I probably searched the word bbox_valid_check in all files.

2023-03-06 19:22 UTC, frheault requested changes

2023-03-06 19:22 UTC, frheault commented on scripts/scil_decompose_connectivity.py
>      sft.remove_invalid_streamlines()
Here you should remove the invalid only if the check is off (if it is one, the check is done internally).
Skipping it if possible would save time.

2023-03-06 19:22 UTC, frheault commented on scripts/scil_remove_invalid_streamlines.py
> -    sft = load_tractogram_with_reference(parser, args, args.in_tractogram,
Considering the nature of the script, I would leave as it was.
100% of the time a user will want the check OFF if they want to remove invalid.
So I would revert this one.

2023-03-07 14:19 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-03-07 21:37 UTC, merged