(WIP) Adding script to apply transform to bvecs
scilus/scilpy pull request #696
Opened 2023-03-20 19:23 UTC by karanphil

Small script based on the `scil_apply_transform_to_image.py` script. It takes as input a bvecs file and a transformation matrix and applies that matrix on the vectors. Pretty straightforward, but I would like people to test it, I might have missed something. @AlexVCaron @arnaudbore

2023-03-20 19:54 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-03-20 20:41 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-696/2/

2023-03-20 20:53 UTC, AlexVCaron requested changes

2023-03-20 20:53 UTC, AlexVCaron commented on scripts/scil_apply_transform_to_bvecs.py
> +    transfo = load_matrix_in_any_format(args.in_transfo)
You can preselect the rotation only here
```suggestion
    transfo = load_matrix_in_any_format(args.in_transfo)[:3, :3]

```

2023-03-20 21:31 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-03-20 22:02 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-03-21 15:23 UTC, arnaudbore approved these changes

2023-03-21 15:24 UTC, merged