Get version script
scilus/scilpy pull request #703
Opened 2023-04-02 20:45 UTC by frheault

Script to help us all debug collaborators when they are not familiar with Git.
This should be used when a collaborator was setup some time ago and we forgot how.

It will be useful in a while (when everyone is up-to-date), but I believe it will be useful.
Could also be a quick way to check 'version' when working across multiple devices/containers/clusters

It outputs:
```
You installed Scilpy with pip on 2023-04-02
The closest release is 1.5

Your Scilpy directory is: /home/frheault/Libraries/scilpy
Your current Origin is: git@github.com:frheault/scilpy.git
Your repository is on branch: get_version_script

The last commit hash is: 2414097218727a5ae4c28677cfe251fec2ec1b6e
The last commit date is: 2023-04-02, by frheault
The last commit message is: Clean pep8

Your upstream is set to: https://github.com/scilus/scilpy.git
You are 0 commits behind upstream/master
You are 3 commits ahead of upstream/master
```

2023-04-02 21:16 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-04-03 15:50 UTC, AlexVCaron requested changes
Very useful, love it !

2023-04-03 17:29 UTC, frheault commented on scripts/scil_get_version.py
> +    for dist in dists:
That could be an option? Or default?

2023-04-03 17:29 UTC, frheault commented on scripts/scil_get_version.py
> +    repo = git.Repo(repo_dir)
That's a good point I will add it!

2023-04-03 18:21 UTC, AlexVCaron commented on scripts/scil_get_version.py
> +    for dist in dists:
I would like Python as default, the rest can be optional for sure

2023-04-03 18:56 UTC, frheault commented
New output after comments (with `--show_dependencies`)

```
Your Python version is: 3.10.6
     dipy: 1.6.1rc1
     dmri-amico: 1.5.4
     dmri-commit: 1.6.4
     nibabel: 4.0.2
     numpy: 1.23.5
You installed Scilpy with pip on 2023-04-03
The closest release is 1.5

Your Scilpy directory is: /home/rhef1902/Libraries/python/scilpy
Your current Origin is: git@github.com:frheault/scilpy.git
Your repository is on branch: get_version_script

The last commit hash is: 54a4108c85a6c7f4582958af82e5108e7e4b90b3
The last commit date is: 2023-04-03, by frheault
The last commit message is: Adress Alex comments

Your upstream is set to: git@github.com:scilus/scilpy.git
You are 0 commits behind upstream/master
You are 7 commits ahead of upstream/master
```

2023-04-03 19:25 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-04-11 18:47 UTC, arnaudbore commented
Not sure if it's a use case you want to cover but I checkout your branch and end up having an error.
```
git checkout francois/get_version_script

scil_get_version.py --show_dependencies
Your Python version is: 3.10.9
     dipy: 1.6.1rc1
     dmri-amico: 1.5.4
     dmri-commit: 1.6.4
     nibabel: 4.0.2
     numpy: 1.23.5
You installed Scilpy with pip on 2023-04-11
The closest release is 1.5

Traceback (most recent call last):
  File "/home/bore/.virtualenvs/scilpy_3.10/bin/scil_get_version.py", line 33, in <module>
    sys.exit(load_entry_point('scilpy', 'console_scripts', 'scil_get_version.py')())
  File "/home/bore/p/scil/s/scilpy/scripts/scil_get_version.py", line 66, in main
    branch = repo.active_branch.name
  File "/home/bore/.virtualenvs/scilpy_3.10/lib/python3.10/site-packages/git/repo/base.py", line 896, in active_branch
    return self.head.reference
  File "/home/bore/.virtualenvs/scilpy_3.10/lib/python3.10/site-packages/git/refs/symbolic.py", line 309, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '54a4108c85a6c7f4582958af82e5108e7e4b90b3'
```

2023-04-12 20:29 UTC, frheault commented
Ok I think now it should work.
The problem was that if you have a remote for my account (frheault)
You can fetch my branch with `git fetch frheault get_version_script`
and for the checkout you can use `git checkout frheault/get_version_script` or `git checkout get_version_script`.

The first one makes the HEAD detached and not the other one
Now both way to checkout work on Linux, testing on a Mac would be neat

2023-04-12 20:45 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-04-12 20:56 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-04-13 13:43 UTC, merged