Correct ihMTsat
scilus/scilpy pull request #732
Opened 2023-08-04 14:13 UTC by karanphil

Here is a small modification to the computation of ihMTsat. Previously, it was in fact the ihMTdR1sat that was calculated. To output this metric, use the `--legacy_sat` option. If not, the real ihMTsat will be computed.

@Manonedde

2023-08-04 14:39 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-15 19:37 UTC, Manonedde requested changes

2023-08-15 19:37 UTC, Manonedde commented on scripts/scil_compute_ihMT_maps.py
> +                   help='Use this option to choose the ihMTdR1sat contrast.')
I will add a "Not recommended" in the help of the --legacy_sat option.

2023-08-16 14:47 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-16 14:49 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-16 14:57 UTC, merged