Working synb0 wrapper in scilpy
scilus/scilpy pull request #734
Opened 2023-08-15 17:41 UTC by frheault

By providing a skull strip t1w and b0, this generate a perfect b0 without distortion which can be fed to topup (saying it has infinite bandwitdh) to trick topup into fixing the diffusion without a rev_b0.

Useful when no rev_b0 is available. Could help to simplify Tractoflow?

https://pubmed.ncbi.nlm.nih.gov/31075422/

2023-08-15 18:42 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-15 19:30 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-734/2/

2023-08-16 16:29 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-734/3/

2023-08-17 12:30 UTC, frheault commented
The test requires tensorflow, should I just delete the test or we turn it off?

2023-08-17 15:59 UTC, AlexVCaron commented
Could the test run conditionally to having Tensorflow installed ? https://stackoverflow.com/questions/36377625/how-to-conditionally-skip-a-test-in-python

Maybe the import error is too early and would prevent this to work ...

2023-08-17 20:21 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-09-27 19:54 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-20 20:49 UTC, arnaudbore reviewed
Need some testing before moving forward. Overall synthesize_b0 works well but still needs to be tested with topup.

2023-10-20 20:49 UTC, arnaudbore commented on scripts/scil_prepare_topup_command.py
> +    print(acqparams)
Remove print

2023-10-20 20:49 UTC, arnaudbore commented on scilpy/utils/image.py
> +                   transformation_type='affine', dwi=None, fine=False):
we need some docstring here

2023-10-23 18:43 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-23 19:35 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-11-02 19:13 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-734/9/

2023-11-08 17:24 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-11-17 16:21 UTC, mdesco reviewed
A few minor comments. Hard for me to test on my mac. Don't want to fight with tensorflow...

2023-11-17 16:21 UTC, mdesco commented on scripts/scil_synthesize_b0.py
> +                   help='Input b0 image.')
Skull-Stripped or not? You mention above that the b0 must skull-strip a few times... Please clarify... 

Idem for the T1 below

2023-11-17 18:32 UTC, mdesco approved these changes
Once the minor comments are done. All good

2023-12-04 19:01 UTC, frheault commented on scripts/scil_synthesize_b0.py
> +- tensorflow
Dipy does not say either.

2023-12-14 16:15 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-12-18 20:44 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-12-21 15:34 UTC, smeisler commented
Thanks for your work on this, I have started testing it out.

It doesn't seem like the synb0 template fetcher function is defined in the PR, but I presume the template was the file in `/data/mni_icbm152_t1_tal_nlin_asym_09c_masked_2_5.nii.gz`? If so, the template looked strange after I visualized it when I downloaded it from GitHub:
<img width="696" alt="image" src="https://github.com/scilus/scilpy/assets/27028726/e6690bc2-1434-4b3e-a1e9-8e793abac7fa">

The resulting b0 map also looked odd, but likely due to trying to register to that odd template image:
<img width="398" alt="image" src="https://github.com/scilus/scilpy/assets/27028726/a787d7a0-3c6e-4aaa-8a12-1c4509ece422">

2023-12-21 15:37 UTC, smeisler commented
Perhaps you should put this file instead in /data: https://github.com/MASILab/Synb0-DISCO/blob/master/atlases/mni_icbm152_t1_tal_nlin_asym_09c_mask.nii.gz

2023-12-21 15:38 UTC, smeisler commented
The template here looks better: https://github.com/MASILab/Synb0-DISCO/blob/master/atlases/mni_icbm152_t1_tal_nlin_asym_09c_mask_2_5.nii.gz

2023-12-21 15:42 UTC, smeisler commented
Fixing the template did the trick!
<img width="400" alt="image" src="https://github.com/scilus/scilpy/assets/27028726/12e77cb0-2f45-4ec2-aebb-adb46091a781">

2023-12-22 15:01 UTC, frheault commented
> The template here looks better: https://github.com/MASILab/Synb0-DISCO/blob/master/atlases/mni_icbm152_t1_tal_nlin_asym_09c_mask_2_5.nii.gz

I will fix the function and make sure the data inside the repo is reuploaded correctly, thank you !

2024-01-12 21:00 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-01-15 14:56 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-02-21 19:05 UTC, arnaudbore requested changes
A couple of comments, almost GTG

2024-02-21 19:05 UTC, arnaudbore commented on scripts/tests/test_synthesize_b0.py
> +from scilpy.io.fetcher import fetch_data, get_home, get_testing_files_dict
Rename this file and edit this file so it actually tests: `scil_volume_b0_synthesis.py`

2024-02-21 19:05 UTC, arnaudbore commented on scilpy/image/volume_operations.py
> +import inspect
inspect and os does not seem to be used here

2024-02-22 13:57 UTC, merged