Add rejected streamlines to scil_filter_tractogram_anatomically
scilus/scilpy pull request #740
Opened 2023-08-30 03:34 UTC by arnaudbore

2023-08-30 04:01 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-30 04:08 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-30 15:12 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-30 15:26 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-08-31 17:07 UTC, AlexVCaron commented on scripts/scil_filter_tractogram_anatomically.py
> +                save_tractogram(outliers_sft, rejected_sft_name)
`outlier_sft` is empty if `args.save_intermediate_tractograms` is false. Do you mean `initial_sft` here ?

2023-08-31 17:08 UTC, AlexVCaron commented on scripts/scil_filter_tractogram_anatomically.py
> +                save_tractogram(outliers_sft, rejected_sft_name)
Same as https://github.com/scilus/scilpy/pull/740#discussion_r1311943047

2023-08-31 17:08 UTC, AlexVCaron commented on scripts/scil_filter_tractogram_anatomically.py
> +                save_tractogram(outliers_sft, rejected_sft_name)
Same as https://github.com/scilus/scilpy/pull/740#discussion_r1311943047

2023-08-31 17:09 UTC, AlexVCaron commented on scripts/scil_filter_tractogram_anatomically.py
> +                save_tractogram(outliers_sft, rejected_sft_name)
Same as https://github.com/scilus/scilpy/pull/740#discussion_r1311943047

2023-08-31 17:12 UTC, AlexVCaron commented on scripts/tests/test_filter_tractogram_anatomically.py
Can you add separate tests for options ? At least one for --save_rejected and another for --save_intermediate_tractograms for now since those mechanisms are weaved together. No need to validate outputs

2023-08-31 17:12 UTC, AlexVCaron requested changes
First comments. I will do a test and get back to you.

2023-08-31 17:53 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-09-06 17:05 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-09-06 19:25 UTC, AlexVCaron approved these changes
Everything seems to be working good on my side. LGTM !

2023-09-07 02:55 UTC, merged