[WIP] Connectomics module
scilus/scilpy pull request #764
Opened 2023-10-13 19:11 UTC by EmmaRenauld

** This is based on the volume_module PR, which should be merged first. **

Next step in the refactoring (and to the preparation of the scil retreat): Managing scripts using connectivity. Once again, no code was changed, only moved.

Now, the main are empty (and more-or-less proof-read), for scripts:
- scil_print_connectivity_filenames.py 
- scil_compare_connectivity.py 
- scil_reorder_connectivity.py 
- scil_evaluate_connectivity_graph_measures.py 
- scil_normalize_connectivity.py     (one line of code was changed: remove the copy(in_matrix) as discussed on teams)

Some functions are placed in connectivity.utils (renamed connectivity.connectivity_tools as it has become more important), others are in stats.matrix_stats. 

Unit tests are not created. 

Scripts that remain because they are more complex and can be managed later:
- scil_compute_connectivity.py
- scil_decompose_connectivity.py
- scil_save_connections_from_hdf5.py
- scil_connectivity_math.py
- scil_filter_connectivity.py 

------
Question: import bct: not listed in requirements. I added something like Charles did for pyopencl. Ok?

Remark: pytest warnings:
- reorder_connectivity script: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix. Ok?
- evaluation_connectivity_graph_measures: RuntimeWarning: invalid value encountered in double_scalars. (dans omega_..) ok?

2023-10-13 19:11 UTC, pep8speaks commented
Hello @EmmaRenauld, Thank you for submitting the Pull Request !

* In the file [`scilpy/connectivity/connectivity_tools.py`](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/connectivity/connectivity_tools.py):

> [Line 152:80](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/connectivity/connectivity_tools.py#L152): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)

* In the file [`scilpy/connectivity/tests/test_connectivity_tools.py`](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/connectivity/tests/test_connectivity_tools.py):

> [Line 21:9](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/connectivity/tests/test_connectivity_tools.py#L21): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file









* In the file [`scilpy/stats/matrix_stats.py`](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/stats/matrix_stats.py):

> [Line 81:80](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/stats/matrix_stats.py#L81): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 97:80](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/stats/matrix_stats.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 168:80](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/stats/matrix_stats.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)



* In the file [`scilpy/stats/tests/test_matrix_stats.py`](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/stats/tests/test_matrix_stats.py):

> [Line 10:9](https://github.com/scilus/scilpy/blob/0ce8a96211b67422ed80dab231d58b4537c59aad/scilpy/stats/tests/test_matrix_stats.py#L10): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2023-10-13 19:45 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-16 20:18 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-17 18:15 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-17 18:31 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-20 17:56 UTC, arnaudbore approved these changes
LGTM waiting for @frheault review before merging

2023-10-20 18:26 UTC, AlexVCaron requested changes
Most of the new files are missing a newline at the end. The should also be a newline between the doctring and the beginning of the code in the functions.

Maybe we let that as is for now and auto-reformat the whole scilpy codebase with autopep8 or something when the whole refactoring is done. We have to configure pep8 bettter so the code standards are better enforced.

2023-10-20 18:26 UTC, AlexVCaron commented on scilpy/connectivity/connectivity_tools.py
> +def parse_ordering(in_ordering_file, labels_list=None):
Move this to IO

2023-10-20 18:26 UTC, AlexVCaron commented on scripts/scil_normalize_connectivity.py
>          assert_inputs_exist(parser, [atlas_filepath, labels_filepath])
Place assert at top of the script to prevent processing if the files aren't available

2023-10-21 01:10 UTC, frheault approved these changes
I like how it is organized! It is ready for Monday (after Alex comment)

2023-10-23 13:53 UTC, EmmaRenauld commented
> Most of the new files are missing a newline at the end.

I don't see that they are missing... Github's pep8 would have told me (I'm usually indeed forgetting them!) Github hides them in the preview I think.

> There should also be a newline between the doctring and the beginning of the code in the functions.

That's not done in most files so yes, let's keep it for later.

2023-10-23 14:31 UTC, AntoineTheb approved these changes
I see no glaring style errors and have not verified the code as its only being moved around. LGTM then.

2023-10-23 16:07 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-23 16:08 UTC, merged