RF - changed tracking default sphere from symmetric724 to repulsion724
scilus/scilpy pull request #769
Opened 2023-10-23 14:21 UTC by gabknight

The `symmetric724` sphere is suboptimal for probabilistic tractography because the vertex density is higher at the poles. 

- Change default sphere to `repulsion724`. This change affects all scripts with input spheres.
- Change the default sphere for GPU tracking. **[need testing]**

2023-10-23 15:17 UTC, CHrlS98 requested changes
For GPU tracking the get_sphere is called in `scilpy.tracking.tracker.GPUTracker._track()` https://github.com/scilus/scilpy/blob/44622e5bdc6ed7ab63b76ce81842da91c8c0f576/scilpy/tracking/tracker.py#L558. Please also change + we could make it an editable parameter while you're at it (if you wanna put the time, was on my todo anyway).

2023-10-23 15:21 UTC, CHrlS98 reviewed
Also we use it as an hemisphere and not a whole sphere, see line 126
https://github.com/scilus/scilpy/blob/44622e5bdc6ed7ab63b76ce81842da91c8c0f576/scripts/scil_compute_local_tracking.py#L126

I don't know in that case if repulsion724 is still better than symmetric724?

2023-10-23 15:32 UTC, gabknight commented
ok thx @CHrlS98. I will check this in GPU tracker. Yes, the repulsion spheres in dipy play well with hemisphere.

2023-10-23 16:04 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-23 19:54 UTC, pep8speaks commented
Hello @gabknight, Thank you for updating !





* In the file [`scripts/scil_compute_local_tracking.py`](https://github.com/scilus/scilpy/blob/7297938f60118fd04af57eafc120b1f6b5613bb0/scripts/scil_compute_local_tracking.py):

> [Line 374:9](https://github.com/scilus/scilpy/blob/7297938f60118fd04af57eafc120b1f6b5613bb0/scripts/scil_compute_local_tracking.py#L374): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2023-10-23 20:27 UTC, CHrlS98 approved these changes

2023-10-23 21:00 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-23 21:25 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-25 13:57 UTC, arnaudbore commented on scripts/scil_compute_local_tracking.py
> +        `repulsion724` and `--sub_sphere` is not available for GPU tracking.
I don't understand, does sub_sphere works with GPU now or not ?

2023-10-26 13:57 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2023-10-26 14:53 UTC, arnaudbore approved these changes

2023-10-26 14:54 UTC, merged