MT/ihMT scripts: cleanup and adding B1+ correction
scilus/scilpy pull request #870
Opened 2023-12-15 22:45 UTC by karanphil

Hi,

I added B1+ field inhomogeneity correction to `scil_mti_maps_MT.py` and `scil_mti_maps_ihMT.py`. Doing so, I also cleaned up those scripts and the functions they call in `scilpy.reconst.mti`. I also added a script (`scil_mti_adjust_B1_header.py`) to correct the bug in the B1 map header, with the scaling issue. There is now a new correction method for B1+, called "model_based" and it requires .mat files obtained with Matlab at the moment. I will send these to the reviewers.

I tested the scripts and they produce the same results as before (without B1 correction). @Manonedde, you should still test them to make sure everything works fine.

This PR doesn't have to be merged quickly.

2023-12-15 22:45 UTC, pep8speaks commented
Hello @karanphil, Thank you for submitting the Pull Request !

* In the file [`scilpy/reconst/mti.py`](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scilpy/reconst/mti.py):

> [Line 152:1](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scilpy/reconst/mti.py#L152): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 318:80](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scilpy/reconst/mti.py#L318): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 319:80](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scilpy/reconst/mti.py#L319): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 378:22](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scilpy/reconst/mti.py#L378): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file



* In the file [`scripts/scil_mti_maps_MT.py`](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py):

> [Line 16:74](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L16): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 60:61](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L60): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 148:1](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L148): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 172:1](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L172): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 229:50](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L229): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 259:54](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L259): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 260:64](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L260): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 323:24](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L323): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 336:29](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_MT.py#L336): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

* In the file [`scripts/scil_mti_maps_ihMT.py`](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py):

> [Line 19:71](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L19): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 66:56](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L66): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 193:1](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L193): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 271:54](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L271): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 272:64](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L272): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 326:37](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L326): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 327:37](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L327): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 333:25](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L333): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 346:29](https://github.com/scilus/scilpy/blob/5b6baaff5cc07427fa762ce93702c8bfb4429388/scripts/scil_mti_maps_ihMT.py#L346): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2023-12-15 23:29 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-870/3/

2023-12-16 23:03 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-870/4/

2024-01-11 15:33 UTC, arnaudbore commented
Build Failed :boom: 
https://jenkins.scil.usherbrooke.ca/job/scilpy/job/PR-870/8/

2024-01-11 19:11 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-01-12 21:02 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-01-16 15:53 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-01-25 17:26 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-01-25 19:20 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-02-05 20:42 UTC, Manonedde requested changes
Some details for Warning messages, otherwise it's good for me!

2024-02-05 20:42 UTC, Manonedde commented on scripts/scil_mti_maps_MT.py
> +                                'affected.'.format(curr_json))
With INFO:root messages, the Warning message goes unnoticed, perhaps with an \n before and/or after it?

2024-02-05 20:42 UTC, Manonedde commented on scripts/scil_mti_maps_MT.py
> +                                'affected.')
With INFO:root messages, the Warning message goes unnoticed, perhaps with an \n before and/or after it?

2024-02-05 21:30 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-02-06 00:38 UTC, Manonedde approved these changes

2024-02-06 14:45 UTC, arnaudbore commented
Build passed ! Good Job :beers: !

2024-02-21 16:06 UTC, merged