Tractogram scripts parts3
scilus/scilpy pull request #958
Opened 2024-03-28 15:57 UTC by EmmaRenauld

# Quick description

Next step of scripts verification.
- `scil_tractogram_detect_loops`: 
      - Clarified the argparser: arguments --qb and --threshold were either both required or both not used, so they were basically the same argument. Merged. 
      - Added a --no_empty option.
- `scil_tractogram_dpp_math`:
      -   argument --out_name was not really the output tractogram name, but the output dpp/dps name. Confusing. Changed to --out_key_name.
      - Moved some checks higher to do them before loading stuff.
      - Added more tests for better code coverage.
- `scil_tractogram_extract_ushape`: 
      - Using `ranged_type`; verifications not needed anymore.
      - Moving stuff a bit.
      - There was a return (old line 88) that could potentially prevent the rest of happening (print counts, save remaining_tractogram). Fixed.

Other changes:

- New compression_arg in all script using compression.
- Deleted the `filter_tractogram_data` method. Confirmed with François: All this is just the equivalent of sft[idx].

## Type of change

Check the relevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Provide data, screenshots, command line to test (if relevant)

...

# Checklist

- [x] My code follows the style guidelines of this project (run [autopep8](https://pypi.org/project/autopep8/))
- [x] I added relevant citations to scripts, modules and functions docstrings and descriptions
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I moved all functions from the script file (except the argparser and main) to scilpy modules
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-03-28 15:58 UTC, pep8speaks commented
Hello @EmmaRenauld, Thank you for submitting the Pull Request !



* In the file [`scilpy/tracking/utils.py`](https://github.com/scilus/scilpy/blob/3556cb4969bc4b33055ee271bce8d9f1287cc3bf/scilpy/tracking/utils.py):

> [Line 142:47](https://github.com/scilus/scilpy/blob/3556cb4969bc4b33055ee271bce8d9f1287cc3bf/scilpy/tracking/utils.py#L142): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

2024-04-10 18:43 UTC, arnaudbore approved these changes
Seems GTG

2024-04-11 15:26 UTC, CHrlS98 requested changes

2024-04-11 15:26 UTC, CHrlS98 commented on scripts/scil_tractogram_smooth.py
> +control points. The control points for the spline fit will be the resampled
I know you didn't change this sentence, but looking at the code, it is not the control points that form the resampled streamline. The control points are used to parameterize the spline and then the resampled streamline is obtained by evaluating the spline at constant intervals.

2024-04-11 18:50 UTC, EmmaRenauld commented on scilpy/io/streamlines.py
> +                                       bbox_valid_check=True):
Ok, but juste save_tractogram will have the same name as dipy's. Is that a problem?

2024-04-11 19:09 UTC, CHrlS98 commented on scilpy/io/streamlines.py
> +                                       bbox_valid_check=True):
Not to me, could we always use this one instead of DIPY's? (we don't need to make the change everywhere in the code for now).

2024-04-12 17:40 UTC, CHrlS98 approved these changes

2024-04-15 13:19 UTC, merged